simulation:
  costs:
    cpu_core: 1
    ram_gb: 1

  limits:
    max_cpu: 2
    max_ram_gb: 1

  metrics_poll_interval: 0.1

workload:
  name: 'Factorize'
  image: 063fce619bc1

algorithm:
  episodes: 1

policy:
  max_cost: 100
