cachalot:
  host: 127.0.0.1
  port: 13866

env:
  type: Simulation

  simulation:
    name: simulation

    type: custom

    limits:
      max_cpu: 10
      max_ram_gb: 10

    costs:
      cpu_core: 0.00010
      ram_gb:   0.00001

    metrics_poll_interval: 0.1
    timeout: 60

workload:
  name: 'Factorize'
  image: hippskill/ocs-factorize:0.1.1

algorithm:
  type: FullSearch

  runs_per_instance: 10
  seed: 1337
  probability_threshold: 0.7
  cost_adjust_coef: 1000
  iters: 20
  max_runs_per_iter: 3
  gamma: 0.99

policy:
  type: min_cost_time_limit
  limit: 60
