simulation:
  type: aws

  limits:
    max_cpu: 10
    max_ram_gb: 5

  aws_data_path: simulation/aws/aws.csv

  metrics_poll_interval: 0.1

workload:
  name: 'Factorize'
  image: 063fce619bc1

algorithm:
  type: RandomSearch

  runs_per_instance: 3
  instances_to_evaluate: 5
  seed: 42

  policy:
    max_cost: 1
