simulation:
  type: custom

  limits:
    max_cpu: 10
    max_ram_gb: 10

  costs:
    cpu_core: 0.00010
    ram_gb:   0.00001

  metrics_poll_interval: 0.1
  timeout: 10

workload:
  name: 'Factorize'
  image: 063fce619bc1

algorithm:
  type: CoordinateDescent

  runs_per_instance: 3
  instances_to_evaluate: 5
  seed: 228
  probability_threshold: 0.5
  cost_adjust_coef: 1000
  iters: 10

  policy:
    max_cost: 1
