simulation:
  type: custom

  limits:
    max_cpu: 10
    max_ram_gb: 10

  costs:
    cpu_core: 10
    ram_gb: 1

  metrics_poll_interval: 0.1

workload:
  name: 'Factorize'
  image: 063fce619bc1

algorithm:
  type: CoordinateDescent

  runs_per_instance: 3
  instances_to_evaluate: 5
  seed: 42
  probability_threshold: 0.75
  iters: 10

  policy:
    max_cost: 1
